spring:
  application.name: jooq-practice
  jooq:
    sql-dialect: MySQL
  datasource:
    url: jdbc:mysql://localhost:13306/sakila
    username: root
    password: passwd
    driverClassName: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.jooq.tools.LoggerListener: DEBUG